services:
  subscriptions-server:
    build:
      context: .
    restart: unless-stopped
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
    ports:
      - "8180:8080"
    depends_on:
      - postgres
    networks:
      - subscriptions-network
  postgres:
    image: postgres:17.2-alpine
    hostname: subscriptions-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5180:5432"
    networks:
      - subscriptions-network

networks:
  subscriptions-network:
    driver: bridge

volumes:
  postgres-data: